### ISSUE TITLE
Slick Forum Issue (last resort post)

### ISSUE THREAD

**Issue by MeMeek** [nguillaumin/slick2d-maven#14]
Hello,

I'm posting here as a last resort. It seems i can't receive any confirmation e-mail after registration on the slick forum, no matter how many times I try. I've 2 non-validated accounts atm : Refact and MeMeek. I didn't fin any admin e-mail adress so i'm helpless.

Would you be so kind as to ask an admin to try to fix this ? I've been trying for a whole week I believe.

My email is en#in%gmath%#     @free.fr (remove all # and % in the first part).

Thanks in advance.

MeMeek/Refact

**Comment by nguillaumin** [comment]
Sorry, but I don't know anybody from the forums!

**Comment by MeMeek** [comment]
Thanks anyways. Sry for posting here.
