### ISSUE TITLE
FIX avoid width and hight check for objectgroup in TiledMap

### ISSUE THREAD

**Issue by HerrDerb** [nguillaumin/slick2d-maven#22]
The inner class `ObjectGroup` still checks for `hight` and `width` on an object layer and fails if not available. This attributes are no longer supported by Tiled as they make no sense.

Useage needs to be removed

Offering a PullRequest

**Comment by nguillaumin** [comment]
Hi, Slick hasn't really kept up with Tiled changes so it's indeed quite possible that there are inconsistencies like that.

Happy to take a pull request, but I guess it would need to cater for old Tiled format vs. new to be backwards compatible?

**Comment by stefanhendriks** [comment]
I believed Slick was dead and abandoned? If not, then it would be great to use this Repo to keep it up to date.

**Comment by nguillaumin** [comment]
Oh yeah it is abandoned. I setup this repo initially to publish Slick on Maven Central, but since then a few people have been submitting pull requests with bug fixes. Usually I merge them and publish a new version on Central.

**Comment by HerrDerb** [comment]
Fair enough. I've switched to https://github.com/mini2Dx

**Comment by nguillaumin** [comment]
No worries, looks like a cool library!

**Comment by HerrDerb** [comment]
Yes, it's quite a "slick"  ;) library from a very active and responsive dev
